### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by xxxxxxripple** [segrax/xrp-wallet#1]
hello i have a problem , i created new xrp cold wallet and after i exchanged some btc into xrp and inserta the address from the cold wallet to recieve the xrp , the transaction was finished from the exchange site but i never got the xrp into my cold wallet. what do i have to do to recieve it?

**Comment by segrax** [comment]
Hi,

This is a 100% cold wallet (it contains no ability to communicate with the network), so you wont see any changes in the actual interface, unless you make them yourself,

But what you can do, if you take the account address and plug it into the Ripple account explorer,
https://charts.ripple.com/#/graph

You should see the account balance in the bottom left of the screen,

**Comment by xxxxxxripple** [comment]
and if i want to send how do i do it?

**Comment by segrax** [comment]
Head to the Send tab, 

you should see your address populated in the 'From' field,

Add the destination Ripple address in the 'Pay To' field, enter the amount of XRP and destination tag (if required by the receiving account).

Set the sequence number to 1 (as this is your first transaction, the wallet will track this internally from here on)

Press 'Sign',

From here you have two options,

1. Click 'Show as QR Code', then scan the resulting QR Code into https://binz.io using your mobile phone

2. Copy the entire chunk of text from the box, and paste it into the 'JSON' field on https://ripple.com/build/websocket-tool/  then press 'Send Request'


You can also take the secret key and import it into one of the online services (such as GateHub), or one of the other desktop wallets (eg. Rippex), If you wish to regularly do payments.

**Comment by xxxxxxripple** [comment]
thank you got it now :)

**Comment by segrax** [comment]
You're welcome
